### ISSUE TITLE
Exception thrown in Visual Studios 2015

### ISSUE THREAD

**Issue by Donaldpherman** [verifycode/verifycode#1]
Exception thrown in Visual Studios 2015
here is the log entry.

  <entry>
    <record>1194</record>
    <time>2018/07/26 21:50:13.001</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: position&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotPoint..ctor(ITextSnapshot snapshot, Int32 position)&#x000D;&#x000A;   at CodeXenie.UI.VsixUtil.ConvertToSnapshotSpan(SourceRange sourceRange, ITextSnapshot snapshot) in E:\src\ncs-static\src\CodeXenie\src\UI\VsixUtil.cs:line 22&#x000D;&#x000A;   at CodeXenie.QuickInfo.ViolationQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan&amp; applicableToSpan) in E:\src\ncs-static\src\CodeXenie\src\UI\ViolationQuickInfo\ViolationQuickInfoSource.cs:line 119&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()</description>
  </entry>
</activity>

**Comment by hyodol53** [comment]
thanks for your reporting. this issue has been resolved. Please install the new version.
